name: API and E2E Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-api:
    name: Testes de API
    runs-on: ubuntu-latest

    services:
      api:
        image: node:16
        ports:
          - 3000:3000
        options: --entrypoint "sh -c 'npm install -g json-server && json-server --watch /data/db.json --port 3000'"

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar testes de API
        run: mvn test -Dtest=br.com.test.api.*Test
        env:
          BASE_URL: http://localhost:3000

  test-e2e:
    name: Testes E2E (Cucumber)
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Rodar testes E2E com Maven
        run: mvn test -Dtest=br.com.test.runners.TestRunner
        env:
          HEADLESS: true
